name = "TMTMPack"
prefix = "tmtm_pack"
author = "TMTM"
files = [
	"mod.cpp",
	"README.md",
	"LICENSE.md",
	"tmtm_logo.paa",
	"tmtm_pack.paa",
	"tmtm_pack_over.paa",
	"tmtm_pack_picture.paa"
]

key_name = "{{prefix}}_{{version}}"
authority = "{{prefix}}_{{version}}-{{git \"id 8\"}}"

check = [
    "!binarizer_link"
]
releasebuild = [
    "@zip tmtmpack_{{semver.major}}.{{semver.minor}}.{{semver.patch}}"
]

[header_exts]
version= "{{git \"id 8\"}}"

# Binarizer file search compatibility
[scripts.binarizer_link]
steps_windows = [
    "if not exist tmtm\\pack mkdir tmtm\\pack",
    "if not exist tmtm\\pack mklink /j tmtm\\pack addons",
	"if not exist a3 mklink /j a3 include\\a3"
]

show_output = true