name = "TMTMPack"
prefix = "tmtm_pack"
author = "TMTM"
files = [
	"mod.cpp",
	"README.md"
]

key_name = "{{prefix}}_{{version}}"
authority = "{{prefix}}_{{version}}-{{git \"id 8\"}}"

[header_exts]
version= "{{git \"id 8\"}}"