name = "TMTMPack"
author = "TMTM"
prefix = "tmtm_pack"

[files]
include = [
	"mod.cpp",
	"README.md",
	"LICENSE.md",
	"tmtm_logo.paa",
	"tmtm_pack.paa",
	"tmtm_pack_over.paa",
	"tmtm_pack_picture.paa"
]
exclude = [
	"*.psd",
	"*.xcf"
]

[version]
path = "addons/main/script_version.hpp"
git_hash = 0

# [properties]
# version = "{{git \"id 8\"}}"

[hemtt.release]
sign = true
archive = true

key_name = "{{prefix}}_{{version}}"
authority = "{{prefix}}_{{version}}-{{git \"id 8\"}}"

# check = [
#     "!binarizer_link"
# ]
# releasebuild = [
#     "@zip tmtmpack_{{semver.major}}.{{semver.minor}}.{{semver.patch}}"
# ]


# # Binarizer file search compatibility
# [scripts.binarizer_link]
# steps_windows = [
#     "if not exist tmtm mkdir tmtm",
#     "if not exist tmtm\\pack mklink /j tmtm\\pack addons",
# ]

# show_output = true
